<?php
// Auto-generated by make.  Do not hand-edit.
// See Makefile in source for details..
// Last updated: Thu 20 Jul 2023 08:45:29 AM EDT
$ASSETS =
  '<link rel="stylesheet" href="pub/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N">' .
  '<script src="pub/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2"></script>' .
  '<script src="pub/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct"></script>' .
  "\n";
?>
