# Makefile for copying files downloaded using composer into the proper location
# for use with edocias.
# We only copy the min number of files required from the vendor directory.
# Also, compute the SHA hash to use with the integrity tag.
# We don't want edocias releases to bundle every single file in the vendor directory.
# Also, composer dependency management sucks at asset management.
#
# NOTE: This Makefile does not work on macos, just linux.  This is because there is
# no sha384sum command on macos.  If you're on a Mac, you can use docker to setup
# a linux container where (after installing xdd), you can run make to generate the
# sha files.


BOOTSTRAP_ICON_VENDOR_DIR = vendor/twbs/bootstrap-icons/icons
BOOTSTRAP_ICONS := $(BOOTSTRAP_ICON_VENDOR_DIR)/$(wildcard filetype-*.svg)
BOOTSTRAP_ICON_DIR = icons
SHA384SUM = /usr/bin/sha384sum

_DEFAULT: load_assets.php \
	_ICONS

_ICONS: \
	$(BOOTSTRAP_ICON_DIR)/filetype-aac.svg \
	$(BOOTSTRAP_ICON_DIR)/filetype-ai.svg \
	$(BOOTSTRAP_ICON_DIR)/filetype-bmp.svg \
	$(BOOTSTRAP_ICON_DIR)/filetype-css.svg \
	$(BOOTSTRAP_ICON_DIR)/filetype-cs.svg \
	$(BOOTSTRAP_ICON_DIR)/filetype-csv.svg \
	$(BOOTSTRAP_ICON_DIR)/filetype-doc.svg \
	$(BOOTSTRAP_ICON_DIR)/filetype-docx.svg \
	$(BOOTSTRAP_ICON_DIR)/filetype-exe.svg \
	$(BOOTSTRAP_ICON_DIR)/filetype-gif.svg \
	$(BOOTSTRAP_ICON_DIR)/filetype-heic.svg \
	$(BOOTSTRAP_ICON_DIR)/filetype-html.svg \
	$(BOOTSTRAP_ICON_DIR)/filetype-java.svg \
	$(BOOTSTRAP_ICON_DIR)/filetype-jpg.svg \
	$(BOOTSTRAP_ICON_DIR)/filetype-json.svg \
	$(BOOTSTRAP_ICON_DIR)/filetype-js.svg \
	$(BOOTSTRAP_ICON_DIR)/filetype-jsx.svg \
	$(BOOTSTRAP_ICON_DIR)/filetype-key.svg \
	$(BOOTSTRAP_ICON_DIR)/filetype-m4p.svg \
	$(BOOTSTRAP_ICON_DIR)/filetype-md.svg \
	$(BOOTSTRAP_ICON_DIR)/filetype-mdx.svg \
	$(BOOTSTRAP_ICON_DIR)/filetype-mov.svg \
	$(BOOTSTRAP_ICON_DIR)/filetype-mp3.svg \
	$(BOOTSTRAP_ICON_DIR)/filetype-mp4.svg \
	$(BOOTSTRAP_ICON_DIR)/filetype-otf.svg \
	$(BOOTSTRAP_ICON_DIR)/filetype-pdf.svg \
	$(BOOTSTRAP_ICON_DIR)/filetype-php.svg \
	$(BOOTSTRAP_ICON_DIR)/filetype-png.svg \
	$(BOOTSTRAP_ICON_DIR)/filetype-ppt.svg \
	$(BOOTSTRAP_ICON_DIR)/filetype-pptx.svg \
	$(BOOTSTRAP_ICON_DIR)/filetype-psd.svg \
	$(BOOTSTRAP_ICON_DIR)/filetype-py.svg \
	$(BOOTSTRAP_ICON_DIR)/filetype-raw.svg \
	$(BOOTSTRAP_ICON_DIR)/filetype-rb.svg \
	$(BOOTSTRAP_ICON_DIR)/filetype-sass.svg \
	$(BOOTSTRAP_ICON_DIR)/filetype-scss.svg \
	$(BOOTSTRAP_ICON_DIR)/filetype-sh.svg \
	$(BOOTSTRAP_ICON_DIR)/filetype-svg.svg \
	$(BOOTSTRAP_ICON_DIR)/filetype-tiff.svg \
	$(BOOTSTRAP_ICON_DIR)/filetype-tsx.svg \
	$(BOOTSTRAP_ICON_DIR)/filetype-ttf.svg \
	$(BOOTSTRAP_ICON_DIR)/filetype-txt.svg \
	$(BOOTSTRAP_ICON_DIR)/filetype-wav.svg \
	$(BOOTSTRAP_ICON_DIR)/filetype-woff.svg \
	$(BOOTSTRAP_ICON_DIR)/filetype-xls.svg \
	$(BOOTSTRAP_ICON_DIR)/filetype-xlsx.svg \
	$(BOOTSTRAP_ICON_DIR)/filetype-xml.svg \
	$(BOOTSTRAP_ICON_DIR)/filetype-yml.svg

$(BOOTSTRAP_ICON_DIR)/%.svg: $(BOOTSTRAP_ICON_VENDOR_DIR)/%.svg
	cp $< $@


load_assets.php: \
	pub/bootstrap.min.css \
	pub/bootstrap.min.css.sha \
	pub/bootstrap.bundle.min.js \
	pub/bootstrap.bundle.min.js.sha \
	pub/jquery.min.js \
	pub/jquery.min.js.sha
	echo '<?php' > $@
	echo '// Auto-generated by make.  Do not hand-edit.' >> $@
	echo '// See Makefile in source for details..' >> $@
	echo '// Last updated: ' | tr -d '\012' >> $@
	date >> $@
	echo "XASSETS =" | tr X '\044' >> $@
	echo '  _<link rel="stylesheet" href="pub/bootstrap.min.css" integrity="sha384-' | tr -d '\012' | tr _ '\047' >> $@
	cat pub/bootstrap.min.css.sha | tr -d '\012' >> $@
	echo '">_ .' | tr _ '\047' >> $@
	echo '  _<script src="pub/jquery.min.js" integrity="sha384-' | tr -d '\012' | tr _ '\047' >> $@
	cat pub/jquery.min.js.sha | tr -d '\012' >> $@
	echo '"></script>_ .' | tr _ '\047' >> $@
	echo '  _<script src="pub/bootstrap.bundle.min.js" integrity="sha384-' | tr -d '\012' | tr _ '\047' >> $@
	cat pub/bootstrap.bundle.min.js.sha | tr -d '\012' >> $@
	echo '"></script>_ .' | tr _ '\047' >> $@
	echo '  "\\n";' >> $@
	echo '?>' >> $@

pub/bootstrap.min.css: vendor/twbs/bootstrap/dist/css/bootstrap.min.css
	cp $< $@

pub/bootstrap.min.css.sha: pub/bootstrap.min.css $(SHA384SUM)
	$(SHA384SUM) $< | head -c 96 | xxd -r -p | base64 > $@

pub/bootstrap.bundle.min.js: vendor/twbs/bootstrap/dist/js/bootstrap.bundle.min.js
	cp $< $@

pub/bootstrap.bundle.min.js.sha: pub/bootstrap.bundle.min.js $(SHA384SUM)
	$(SHA384SUM) $< | head -c 96 | xxd -r -p | base64 > $@

pub/jquery.min.js: vendor/components/jquery/jquery.min.js
	cp $< $@

pub/jquery.min.js.sha: pub/jquery.min.js $(SHA384SUM)
	$(SHA384SUM) $< | head -c 96 | xxd -r -p | base64 > $@

